services:
    app:
        # cp app/.env .env
        environment:
            - NGINX_HOST=${APP_NAME}.com
            - NGINX_PORT=80
        build:
            context: .
            dockerfile: infra/docker/development/Dockerfile
            args:
                NGINX_VERSION: ${NGINX_VERSION:-1.26.0-perl}
        working_dir: /srv/app
        volumes:
            - ./app:/srv/app
        ports:
            - "8080:${APP_SERVER_PORT:-80}"
